import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "./components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className='min-h-full'>
        <div className='flex flex-col h-screen w-full'>
          <main className='flex w-full h-full max-w-[1600] text-black mx-auto overflow-hidden'>
            <SideBar />
            <section className='flex-1 h-full overflow-y-auto'>
              {children}
            </section>
          </main>
        </div>
      </body>
    </html>
  );
}
